### ISSUE TITLE
Difference between Qg_tavg in FLDAS vs GLDAS

### ISSUE THREAD

**Issue by dnfeldman** [mintproject/MINT-Raw-Data-Fetcher#2]
Hi @shiyuning, 

I'm reading documentation for [FLDAS](https://hydro1.gesdisc.eosdis.nasa.gov/data/FLDAS/FLDAS_NOAH01_A_EA_D.001/doc/README_FLDAS.pdf) (Table 4.a) and [GLDAS](https://hydro1.gesdisc.eosdis.nasa.gov/data/GLDAS/GLDAS_NOAH025_3H.2.1/doc/README_GLDAS2.pdf) (Table 3.1) and both of them mention parameter `Qg_tavg`. However, in one the description is simply "Heat flux" while in the other it's "Soil heat flux". Should I interpret them as being the same because they have the same short name or distinct because they have different description? Thanks!

**Comment by khider** [comment]
Try to download two of the netcdf files and use the standard_name in the variable properties to make sure they are different.

**Comment by kemanian** [comment]
It is the soil heat flux in both cases.

**Comment by dnfeldman** [comment]
I see, thanks - both seem to have `downward_heat_flux_in_soil`. However, that was only from comparing 2 random netcdf files. Can (should?) we assume that they are going to be the same for the entire dataset? 

Also, ideally data catalog should be getting this information from a source that is not the actual data file because we want to avoid downloading data, if possible...

**Comment by khider** [comment]
Yes, the metadata that would apply to the entire dataset will be the same in random files of the same dataset. 

This is what's powerful with the format. In theory, we could download a file and write a script to populate the data catalog automatically. 

Most of the times the documentation will contain the same information. However, I've often found that it has a lot of errors (as you've just discovered).

**Comment by shiyuning** [comment]
@dnfeldman Armen was right, both are soil heat fluxes. The README for GLDAS was simply wrong. All of the GLDAS-2 files downloaded are generated using the same model so they are the same for the entire dataset.
